version: 0.2
env:
  variables:
    DIST_FOLDER: "dist"
    BUILD_ENV: "dev"
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - echo "Install dependencies"
      - cd src
      - npm install
      - npm run build
      - cd ..
  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      - npm run test
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      - rm -rf ./__tests__
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      #- aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - sam package --template-file template.yaml --output-template-file sample-transformed.yaml --s3-bucket $SAM_BUCKET
artifacts:
  type: zip
  files:
    - template-export.yml
