AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  msa_lab

  Sample SAM Template for msa_lab
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        OrderTable: !Ref orderTable
        PaymentTable: !Ref PaymentTable
        OrderQueue: !Ref OrderQueue

Resources:
  OrderQueue:
    Type: AWS::SQS::Queue

  PaymentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/payment
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /payment
            Method: get

  CouponFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/coupon
      Handler: app.handler
      Runtime: nodejs12.x
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref CouponTable

  PaymentEventHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A lambda function which handle event of member.
      Runtime: nodejs12.x
      CodeUri: src/payment
      Handler: app.eventHandler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrderQueue.Arn
      MemorySize: 256
      Timeout: 25
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSQSFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref PaymentTable

  OrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/order
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 256
      Timeout: 100
      Description: Sample Application Order Doamin
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSQSFullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref orderTable
#       Environment:
#         Variables:
#           ORDER_TABLE: !Ref orderTable
      Events:
        ListMemberApi:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
        CreateMemberApi:
          Type: Api
          Properties:
            Path: /order
            Method: POST

  orderTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: PK
        Type: String
      TableName: MSA_ORDER

  PaymentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: PK
        Type: String
      TableName: MSA_PAYMENT

  CouponTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "Coupon_${Stage}"
      # BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: HASH
        - AttributeName: "SK"
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  MSALabApi:
    Description: "API Gateway endpoint URL for Prod stage for OrderController World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  OrderFunction:
    Description: "Order Lambda Function ARN"
    Value: !GetAtt OrderFunction.Arn
  OrderFunctionIamRole:
    Description: "Implicit IAM Role created for OrderController World function"
    Value: !GetAtt OrderFunctionRole.Arn
  PaymentFunction:
    Description: "Payment Lambda Function ARN"
    Value: !GetAtt PaymentFunction.Arn
  PaymentFunctionIamRole:
    Description: "Implicit IAM Role created for OrderController World function"
    Value: !GetAtt PaymentFunctionRole.Arn
  OrderQueue:
    Description: "Order Queue"
    Value: !GetAtt OrderQueue.Arn

